name: Extract Expressly Zip

on:
  push:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verify files
        run: ls -l

      - name: Unzip Expressly-main.zip
        run: unzip Expressly-main.zip

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Extract Expressly-main.zip"
          git push
